### ISSUE TITLE
serverinfo layout 

### ISSUE THREAD

**Issue by gavrilson** [gearbot/GearBot#112]
Not sure if this will be possible, but, it would be cool to be able to toggle off the roles shown; or at least just to display a number of how many there are instead of the names.

Other cool tiny bits of information would be how many are offline, busy, away and online.

**Comment by AEnterprise** [comment]
statuses def doable, not sure how to make the roles stuff toggle able in an easy way that makes sense

**Comment by AEnterprise** [comment]
offline/busy/away/online is a thing already

per guild settings on what is being shown is something for the dasboard later
