### ISSUE TITLE
Log message pin/unpin events

### ISSUE THREAD

**Issue by Alex1304** [gearbot/GearBot#116]
Because currently on Discord it's hard to track down who pins or unpins a message. From a recent experience where someone abused his powers and unpinned all messages in a channel without ability for anyone to know who did it, having the bot log who pins and unpins messages would be a great addition.

**Comment by Tarek1337** [comment]
This was added a while ago. Unfortunately it doesn't log _who_ removed the pin, but that's a Discord limitation, nothing that can be done on Gearbot's end. :(

Closing issue
