### ISSUE TITLE
When launching the blacklist add command twice and adding formatting, the blacklist breaks.

### ISSUE THREAD

**Issue by Kitty-Therapist** [gearbot/GearBot#371]
**Describe the bug**
After launching the command with blacklist add (twice in one message) with the formatting. You cannot remove that from the blacklist.

**Steps To Reproduce**
- Add the following ``!configure blacklist add !configure blacklist add **test**``
- Try to remove the blacklist by ``!configure blacklist remove !configure blacklist add **test**``

**Expected behavior**
It should remove it from the blacklist like any other words. 

**Screenshots**
https://i.imgur.com/ZIe0pQV.png

**Additional context**
This can tend to happen if you are trying to blacklist a phrase in multiple servers, and you may forget that you have !configure blacklist add added already, and it seems to only break when there are formatting involved. If you do ``!configure blacklist add !configure blacklist add owo`` for example, you can remove it just fine.

**Comment by AEnterprise** [comment]
as per the screenshot you where trying to remove something that isn't on the blacklist at all
![image](https://user-images.githubusercontent.com/5206666/67591012-ab082380-f75c-11e9-9a3c-11c4bfaca822.png)
