### ISSUE TITLE
"I was removed from x server" breakage

### ISSUE THREAD

**Issue by Taarek** [gearbot/GearBot#374]
**Describe the bug**
Apparently if a bot leaves a guild, it's only supposed to get a guild ID and not an entire guild object

**Steps To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
Comment regarding this, it will change in the next API deploy. https://github.com/discordapp/discord-api-docs/issues/714#issuecomment-552252323

**Comment by AEnterprise** [comment]
i'm not sure how this affects gearbot at all, wouldn't d.py just return the guild object from cache instead?

**Comment by Taarek** [comment]
No

**Comment by AEnterprise** [comment]
the new api update was deployed and it is indeed just getting guild objects for this event from cache
