### ISSUE TITLE
Beanboard

### ISSUE THREAD

**Issue by boehs** [gearbot/GearBot#448]
**Describe the bug**
I expected to be able to see a leaderboard of all beans but bean command was lacking and I am disappointed and my day was ruined

**Steps To Reproduce**
1. Do this
2. Do that
4. Wow how do I counr never of beans?????

**Expected behavior**
The bean command is beener then it is currently

**Screenshots**

![Screenshot_20220506-093827](https://user-images.githubusercontent.com/51836263/167144205-ece7b9dd-b78e-4ca6-9ae2-cfd711a6bcf1.png)

**Additional context**
Bean

Maybe make it moderator only

Also bean

Thank you for your time

**Comment by ASF007** [comment]
@AEnterprise this issue is  a “troll” with no actual context.

**Comment by boehs** [comment]
However the bug was a mistake, I think bugs look like beans or beans look like bugs but it's more politically correct to say feature request in this context

**Comment by AEnterprise** [comment]
this is a feature request i have no plans for doing at all

**Comment by boehs** [comment]
> this is a feature request i have no plans for doing at all

If I did would you merge it?

**Comment by AEnterprise** [comment]
No, no because i'd end up having to maintain and port it
