### ISSUE TITLE
Anti-Raid + Improvements

### ISSUE THREAD

**Issue by Kitty-Therapist** [gearbot/GearBot#91]
I just came up with a list of the features that could be implemented into GearBot for any possible situations for any servers.

They are the following:
- Disabling the ping.
- Raising or lowering the amount of users joining by command.
- Have the bot to search for the specific snowflake that we need to look out for - or account creation date.
- Temporarily disables the antiraid. Like I could do !antiraid off 2h <reason>
- Turning it off until you turn it back on

These would be useful for if the server owner (i.e. House of Brilliance) are expecting an mass join due to a major event (i.e. being linked in the Snowsgiving Fire Dumpster server) where up to 20 or more people will join at the same time. 

Currently, with another bot - it will trigger the anti-raid and we will get pinged but we will see that it's just a group of people being curious about the server itself. So if we had a way to customize our options, or handle how we want our anti-raid feature to work. It would be a good feature for GearBot.

**Comment by AEnterprise** [comment]
will be added in moving the anti-raid from outboard to gearbot, partial progress of that at #73
